---
apiVersion: v1
data:
  dbname: {{ .Values.db.name | b64enc }}
  dbpassword: {{ .Values.db.passwd | b64enc }}
  dbuser: {{ .Values.db.user | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: {{ .Values.namespace }}