wordpress:
  # wordpressSkipInstall: true
  htaccessPersistenceEnabled: true
  ingress:
    enabled: true
    hostname: selfasteam.co.uk
    tls: true
    selfSigned: false
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
  service:
    type: ClusterIP

  persistence:
    size: 50Gi

  mariadb:
    enabled: false
  externalDatabase:
    host: mariadb.mariadb.svc.cluster.local
    port: 3306
    database: selfasteam
    user: selfasteam
    existingSecret: db-password

  memcached:
    enabled: true
