wordpress:
  # wordpressSkipInstall: true
  htaccessPersistenceEnabled: true
  ingress:
    enabled: true
    hostname: selfasteam.co.uk
    tls: true
    selfSigned: false
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
  service:
    type: ClusterIP

  persistence:
    size: 50Gi

  mariadb:
    enabled: false
  externalDatabase:
    host: mariadb.mariadb.svc.cluster.local
    port: 3306
    database: selfasteam
    user: selfasteam
    existingSecret: db-password

  memcached:
    enabled: true

  resources:
    limits:
      cpu: "3"
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi

  livenessProbe:
    httpGet:
      path: /wp-login.php

  customPostInitScripts:
    wordfence.sh: |
      #!/bin/bash
      echo "Fixing wordfence..."
      if ! test -f /opt/bitnami/wordpress/wordfence-waf.php; then
        ln -s /bitnami/wordpress/wordfence-waf.php /opt/bitnami/wordpress/wordfence-waf.php
      fi
      

