onechart:
  image:
    repository: docker.io/vaultwarden/server
    tag: 1.30.5-alpine

  vars: {}

  ingress:
    annotations: {}
    host: vault.devurandom.io
    tlsEnabled: true

  volumes:
    - name: data
      path: /data
      size: 20Gi

  secretName: admin-passphrase

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: 
      - ALL
    privileged: false
    readOnlyRootFilesystem: true                                                                                                                                                  
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  resources:
    limits:
      cpu: "1"
      memory: "512Mi"

  probe:
    enabled: true
    path: '/api/alive'
    settings:
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
      failureThreshold: 3

  podSecurityContext:
    fsGroup: 1000240000