apiVersion: v2
name: owncloud
description: Chart for Owncloud
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: owncloud
  version: 12.2.11
  repository: https://charts.bitnami.com/bitnami