owncloud:
  ingress:
    enabled: true
    hostname: cloud.awali.co.uk
    tls: true
    extraHosts:
    - name: cloud.greeninja.co.uk
      path: /
    - name: cloud.devurandom.io
      path: /
    annotations: {}

  owncloudSkipInstall: true

  mariadb:
    enabled: false

  externalDatabase:
    host: mariadb.mariadb.svc.cluster.local
    port: 3306
    user: owncloud
    database: owncloud
    existingSecret: db-password

  persistence:
    enabled: true
    size: 200Gi

  service:
    type: ClusterIP

  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false