owncloud:
  ingress:
    enabled: true
    hostname: cloud.awali.co.uk
    tls: true
    extraHosts:
    - name: cloud.greeninja.co.uk
      path: /
    - name: cloud.devurandom.io
      path: /
    annotations: {}

  image:
    registry: docker.io
    repository: owncloud/server
    tag: 10.13.4

  extraEnvVars:
  - name: OWNCLOUD_VOLUME_ROOT
    value: /bitnami/owncloud
  - name: OWNCLOUD_SKIP_CHMOD
    value: "true"
  - name: OWNCLOUD_SKIP_CHOWN
    value: "true"
  - name: OWNCLOUD_CROND_ENABLED
    value: "false"
  - name: OWNCLOUD_BACKGROUND_MODE
    value: Webcron
    - name: OWNCLOUD_DB_HOST
    value: mariadb.mariadb.svc.cluster.local
  - name: OWNCLOUD_DB_TYPE
    value: mysql
  - name: OWNCLOUD_DB_USERNAME
    value: owncloud
  - name: OWNCLOUD_TRUSTED_DOMAINS
    value:
      - cloud.awalioilandgas.com
      - owncloud.greeninja.co.uk
      - cloud.greeninja.co.uk
      - cloud.awali.co.uk
      - localhost

  extraEnvVarsSecret: db-password-2
    

  owncloudSkipInstall: true

  mariadb:
    enabled: false

  externalDatabase:
    host: mariadb.mariadb.svc.cluster.local
    port: 3306
    user: owncloud
    database: owncloud
    existingSecret: db-password

  persistence:
    enabled: true
    size: 200Gi

  service:
    type: ClusterIP

  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false