apiVersion: v2
name: passbolt
description: Chart for Passbolt
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: passbolt
  version: 0.7.2
  repository: https://download.passbolt.com/charts/passbolt