apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: cert-manager
    repoURL: https://gitlab.com/greeninja/k8s-argo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=true