metrics-server:
  securityContext:
    runAsUser: 1000221234

  addonResizer:
    securityContext:
      runAsUser: 1000221234
  
  apiService:
    insecureSkipTLSVerify: true

  defaultArgs:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --metric-resolution=15s
  - --kubelet-insecure-tls