apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  image: "11.3.1"
  port: 3306
  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
  service:
    type: ClusterIP
