---
name: mariadb
namespace: mariadb
replicaCount: 1

image:
  repository: docker.io/library/mariadb
  tag: 11.2.2
  pullPolicy: IfNotPresent

containerPort: 3306
mysqlRootPw: password

service:
  type: ClusterIP
  port: 3306

pv:
  size: 10Gi
  type: ReadWriteOnce
