apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: mariadb-secret
  namespace: {{ .Values.namespace }}
data:
  dbrootpassword: {{ .Values.mysqlRootPw | b64enc }}
kind: Secret