velero:
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.9.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  metrics:
    enabled: false
  configuration:
    backupStorageLocation:
      - name: default
        provider: aws
        bucket: nck8svelerobackups
        prefix: k8s-backups
        default: true
        credential:
          name: s3-secret
          key: velero-creds
        config:
          region: eu-west-2
    defaultVolumesToFsBackup: true
    credentials:
      exisitingSecret: s3-secret


  snapshotsEnabled: false
  deployNodeAgent: true

  schedules:
    backup:
      disabled: false
      schedule: "3 0 * * *"
      useOwnerReferencesInBackup: false
      template:
        ttl: "168h"
        storageLocation: default
