minio:
  ingress:
    enabled: true
    hostname: s3-console.devurandom.io
  apiIngress:
    enabled: true
    hostname: s3.devurandom.io
  persistence:
    size: 100Gi
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      memory: 256Mi
      cpu: 100m