apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  # channel: stable
  installPlanApproval: Automatic
  name: mariadb-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  startingCSV: mariadb-operator.v0.23.1
